use findActivity everywhere
theScrabi/NewPlayer pull request #15
Opened 2024-12-22 22:18 UTC by Profpatsch

When adding NewPlayer to NewPipe, we call it from a Fragment, which will not have a direct Activity in Context, but a wrapper class. We already had a function for that but did not call it everywhere. This fixes that.

We should probably assume we can find an Activity everywhere in the player UI. Later.

Also adds two minor changes.

2025-01-03 13:34 UTC, theScrabi requested changes

2025-01-03 13:34 UTC, theScrabi commented on new-player/src/main/java/net/newpipe/newplayer/ui/common/utils.kt
> +  */
Consider adding @hide here, so this function does not show up on the KDoc documentation.

2025-01-03 13:34 UTC, theScrabi commented on new-player/src/main/java/net/newpipe/newplayer/ui/common/utils.kt
> + */
Consider adding @hide here, so this function does not show up on the KDoc documentation.

2025-01-03 13:34 UTC, theScrabi commented on new-player/src/main/java/net/newpipe/newplayer/ui/common/utils.kt
> +@Composable
Consider adding @hide here, so this function does not show up on the KDoc documentation.

2025-01-03 13:34 UTC, theScrabi commented on new-player/src/main/java/net/newpipe/newplayer/NewPlayerImpl.kt
> -
Useful cleanup, but if I'm nitpicky this code change should not be part of this PR.
I don't care too much about this though :P. However, I don't know how other devs feel about this. I'd say do it as you feel best with.

2025-01-03 13:34 UTC, theScrabi commented on new-player/src/main/java/net/newpipe/newplayer/logic/MediaSourceBuilder.kt
> -                val mediaItem = toMediaItem(streamSelection.item, streamSelection.stream, uniqueId)
Same here.

2025-01-03 13:34 UTC, theScrabi commented on new-player/src/main/java/net/newpipe/newplayer/logic/MediaSourceBuilder.kt
> -                        streamSelection.item,
Same here.

2025-01-03 13:34 UTC, theScrabi commented on new-player/src/main/java/net/newpipe/newplayer/logic/StreamExceptionResponse.kt
> -interface StreamExceptionResponse
Same here.

2025-02-26 14:19 UTC, Stypox reviewed
Looks good to me. Have you had time to fix Schabi's suggestions?

2025-06-02 14:57 UTC, merged